export const TOOLS = [
  {
    slug: 'risk-calculator',
    name: 'Risk Calculator',
    short: 'Risk Calc',
    description: 'Calculate the exact dollar amount to risk based on your balance and risk percentage.',
    emoji: '🎯',
    color: 'green',
    metaDesc: 'Free trading risk calculator. Enter your balance and risk % to get the exact dollar amount to risk per trade. Works for forex, gold, indices and crypto.',
  },
  {
    slug: 'position-size-calculator',
    name: 'Position Size',
    short: 'Position Size',
    description: 'Find the correct lot size so your stop loss never exceeds your risk limit.',
    emoji: '📐',
    color: 'green',
    metaDesc: 'Free position size calculator for traders. Calculate the right lot size for any stop loss and risk amount. Forex, gold, indices and crypto.',
  },
  {
    slug: 'risk-reward-calculator',
    name: 'Risk/Reward',
    short: 'R:R Calc',
    description: 'Instantly calculate your risk/reward ratio and potential profit or loss.',
    emoji: '⚖️',
    color: 'amber',
    metaDesc: 'Free risk reward ratio calculator. Enter entry, stop loss and take profit to get your R:R ratio instantly. Essential for every trader.',
  },
  {
    slug: 'drawdown-calculator',
    name: 'Drawdown',
    short: 'Drawdown',
    description: 'See how much recovery is needed after a losing streak.',
    emoji: '📉',
    color: 'red',
    metaDesc: 'Free drawdown calculator for traders. See how a drawdown affects your balance and how much you need to recover. Essential risk management tool.',
  },
  {
    slug: 'compounding-calculator',
    name: 'Compounding',
    short: 'Compound',
    description: 'Project your account growth with consistent monthly returns.',
    emoji: '📈',
    color: 'green',
    metaDesc: 'Free trading compounding calculator. See how your account grows with consistent returns over time. Project your trading goals.',
  },
  {
    slug: 'forex-sessions',
    name: 'Forex Sessions',
    short: 'Sessions',
    description: 'Live forex market session clock — see which markets are open right now.',
    emoji: '🕐',
    color: 'amber',
    metaDesc: 'Live forex session clock. See Tokyo, London, New York and Sydney market hours in real time. Know when each session opens and closes.',
  },
]
